buildscript {
    repositories {
        google()
        jcenter()
        flatDir(dirs: 'libs')
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:**AGPVERSION**'
    }
}

plugins {
    id 'com.android.library'
}

android {
    //namespace 'com.codedimmersions.eostransport.eos_dependencies'
    compileSdkVersion **COMPILESDKVERSION**
    buildToolsVersion **BUILDTOOLSVERSION**

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.**JAVAVERSION**
        targetCompatibility JavaVersion.**JAVAVERSION**
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'androidx.security:security-crypto:1.0.0'
    implementation 'androidx.browser:browser:1.4.0'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:**DESUGARVERSION**'
}